#!/bin/bash

echo "🎯 FINAL COMPREHENSIVE UI VERIFICATION"
echo "===================================="
echo ""

echo "📍 SERVER STATUS CHECK"
echo "====================="
if curl -s http://localhost:3001 > /dev/null; then
    echo "✅ Frontend Server: http://localhost:3001 - RUNNING"
else
    echo "❌ Frontend Server: http://localhost:3001 - NOT RUNNING"
    exit 1
fi

if curl -s http://localhost:3002/health > /dev/null; then
    echo "✅ Backend Server: http://localhost:3002 - RUNNING"
else
    echo "❌ Backend Server: http://localhost:3002 - NOT RUNNING"
    exit 1
fi

echo ""
echo "🔗 LIVE INTERACTION INSTRUCTIONS"
echo "==============================="
echo ""
echo "🌐 STEP 1: Open the Application in Your Browser"
echo "-------------------------------------------"
echo "• URL: http://localhost:3001"
echo "• This is the actual live application interface"
echo ""

echo "👤 STEP 2: Test Registration with Success Message"
echo "-----------------------------------------------"
echo "• Navigate to: http://localhost:3001/register"
echo "• Fill in the registration form:"
echo "  - Username: live_test_user_$(date +%s)"
echo "  - Password: testpass123"
echo "  - Display Name: Live Test User"
echo "• Click the Register/Sign Up button"
echo "• ✅ VERIFY: Look for success message or redirect to login page"
echo ""

echo "🔐 STEP 3: Test Login Functionality"
echo "---------------------------------"
echo "• Navigate to: http://localhost:3001/login"
echo "• Use existing test credentials:"
echo "  - Username: alice"
echo "  - Password: password123"
echo "• Click the Login button"
echo "• ✅ VERIFY: You should be redirected to the main chat interface"
echo ""

echo "🔍 STEP 4: Test Search Other Users Feature"
echo "----------------------------------------"
echo "• In the chat interface, look for search functionality"
echo "• Search for existing users like 'bob' or 'test'"
echo "• ✅ VERIFY: Search results should appear showing found users"
echo ""

echo "💬 STEP 5: Test Starting Conversations"
echo "-------------------------------------"
echo "• Click on a user from search results or conversation list"
echo "• Try to send a message: 'Hello from live testing'"
echo "• ✅ VERIFY: Conversation should start and message should send"
echo ""

echo "🚪 STEP 6: Test Logout"
echo "----------------------"
echo "• Look for logout button or user menu"
echo "• Click logout option"
echo "• ✅ VERIFY: Should be redirected back to login page"
echo ""

echo "🗄️ STEP 7: Verify Data Persistence in Database"
echo "--------------------------------------------"
echo "• After completing the UI tests above, return to this terminal"
echo "• Run this command to verify your data was saved:"
echo ""
echo "    sqlite3 data/chat.db 'SELECT username, display_name, created_at FROM users ORDER BY created_at DESC LIMIT 3'"
echo ""
echo "• ✅ VERIFY: Your test user should appear in the database"
echo ""

echo "📋 CURRENT DATABASE STATE (Before Your Tests)"
echo "============================================"
echo ""
echo "📊 Database Statistics:"
echo "• Total Users: $(sqlite3 data/chat.db 'SELECT COUNT(*) FROM users')"
echo "• Total Conversations: $(sqlite3 data/chat.db 'SELECT COUNT(*) FROM conversations')"
echo ""
echo "👥 Recent Users (Real Data from Previous Tests):"
sqlite3 data/chat.db "SELECT '  • ' || username || ' (' || display_name || ') - Created: ' || created_at FROM users ORDER BY created_at DESC LIMIT 5"
echo ""
echo "💬 Recent Conversations:"
sqlite3 data/chat.db "SELECT '  • Conversation ' || id || ' (Type: ' || type || ') - Created: ' || created_at FROM conversations ORDER BY created_at DESC LIMIT 3"
echo ""

echo "🎯 VERIFICATION CHECKLIST"
echo "======================"
echo ""
echo "✅ Components to Verify Through UI:"
echo "1. [ ] Registration form accessible and functional"
echo "2. [ ] Success message appears after registration"
echo "3. [ ] Login with alice/password123 works"
echo "4. [ ] Redirected to chat interface after login"
echo "5. [ ] Search functionality finds other users"
echo "6. [ ] Can click users to start conversations"
echo "7. [ ] Message sending works in conversations"
echo "8. [ ] Logout button redirects to login page"
echo "9. [ ] Database shows new user after registration"
echo "10. [ ] All changes persisted in database"
echo ""

echo "🔗 ACCESS POINTS"
echo "==============="
echo "• Frontend Application: http://localhost:3001"
echo "• Backend API: http://localhost:3002/api"
echo "• Database File: ./data/chat.db"
echo ""
echo "👥 TEST CREDENTIALS AVAILABLE"
echo "============================"
echo "• Username: alice, Password: password123"
echo "• Username: bob, Password: password456"
echo "• Any newly registered users during testing"
echo ""

echo "🎯 FINAL VERDICT EXPECTED"
echo "========================"
echo "✅ All functionality should work through live UI interface"
echo "✅ Registration success messages should appear"
echo "✅ Login/logout should function properly"
echo "✅ User search should find other users"
echo "✅ Conversations should start successfully"
echo "✅ All data should persist in SQLite database"
echo "✅ No mocked data - only real database records"
echo ""
echo "🚀 START LIVE TESTING NOW!"
echo "=========================="
echo "• Open http://localhost:3001 in your browser"
echo "• Follow the 7 steps above"
echo "• Return to terminal for database verification"
echo ""