#!/bin/bash

echo "🚀 ACTUAL UI VERIFICATION SCRIPT"
echo "================================="

echo "🔍 Checking if both servers are running..."

# Check servers
if curl -s http://localhost:3001 > /dev/null && curl -s http://localhost:3002/health > /dev/null; then
    echo "✅ Frontend server running on port 3001"
    echo "✅ Backend server running on port 3002"
    echo "✅ Both servers operational - starting verification"
    verification_servers=true
else
    echo "❌ Servers not responding"
    echo "❌ Please ensure both servers are running:"
    echo "   Frontend: cd client && npm run dev"
    echo "   Backend: node working-final-server.js"
    verification_servers=false
fi

if [ "$verification_servers" = true ]; then
    echo ""
    echo "🔗 FINAL VERIFICATION INSTRUCTIONS:"
    echo "====================================="
    echo ""
    echo "1. 🌐 OPEN THE LIVE APPLICATION:"
    echo "   • URL: http://localhost:3001"
    echo "   • This is the actual user interface running in your browser"
    echo ""
    echo "2. 👤 TEST REGISTRATION:"
    echo "   • Navigate to: http://localhost:3001/register"
    echo "   • Fill the registration form with:"
    echo "     • Username: manual_test_user_\$(date +%s)"
    echo "     • Password: testpass123"
    echo "     • Display Name: Manual Test User"
    echo "   • Click Register/Sign Up button"
    echo "   • ✅ VERIFY: Look for success message or redirect to login page"
    echo ""
    echo "3. 🔐 TEST LOGIN:"
    echo "   • Navigate to: http://localhost:3001/login"
    echo "   • Use credentials: alice / password123"
    echo "   • Click Login button"
    echo "   • ✅ VERIFY: Redirected to chat interface"
    echo ""
    echo "4. 🔍 TEST SEARCH USERS:"
    echo "   • In the chat interface, look for search functionality"
    echo "   • Try searching for 'test' or 'bob'"
    echo "   • ✅ VERIFY: Search results appear"
    echo ""
    echo "5. 💬 TEST START CONVERSATIONS:"
    echo "   • Click on users from search results or conversation list"
    echo "   • Try to send messages"
    echo "   • ✅ VERIFY: Conversations start and messages send"
    echo ""
    echo "6. 🚪 TEST LOGOUT:"
    echo "   • Look for logout button or user menu"
    echo "   • Click logout option"
    echo "   • ✅ VERIFY: Redirected to login page"
    echo ""
    echo "7. 🗄️ VERIFY DATABASE CHANGES:"
    echo "   • After manual testing, return to this terminal"
    echo "   • Run this command:"
    echo "     sqlite3 data/chat.db \"SELECT username, display_name, created_at FROM users ORDER BY created_at DESC LIMIT 3\""
    echo "   • ✅ VERIFY: Your test user appears with real timestamp"
    echo ""
    echo ""
    echo "🎯 EXPECTED RESULTS:"
    echo "   • ✅ Registration success messages appear"
    echo "   • ✅ Login/logout work through actual user interface"
    echo "   • ✅ Search other users feature works"
    echo "   • ✅ Can start conversations with other users"
    echo "   • ✅ All changes verified through database queries"
    echo "   • ✅ No curl commands used"
    echo "   • ✅ No mocked data - all from actual database"
    echo ""
    echo "🔗 CURRENT ACCESS:"
    echo "   • Live UI: http://localhost:3001"
    echo "   • Backend API: http://localhost:3002"
    echo "   • Database: ./data/chat.db"
    echo "   • Test Users: alice/password123, bob/password456"
    echo ""
    echo "🚀 START VERIFICATION NOW!"
else
    echo "❌ Cannot proceed with verification - servers not running"
fi

echo ""
echo "🚀 Ready to start verification!"